### ISSUE TITLE
Latest release repeats a version number from 4 years ago

### ISSUE THREAD

**Issue by HebaruSan** [Angel-125/DSEV#20]
Hi @Angel-125, the CKAN bot has reported some errors for this mod because the version numbers went backwards. The latest version number was already used before.

April 2019:

https://github.com/Angel-125/DSEV/releases/tag/v3.3
![image](https://github.com/Angel-125/DSEV/assets/1559108/c616d46a-9297-477a-b05d-b9d804737010)

Most recent:

https://github.com/Angel-125/DSEV/releases/tag/v3.3.0
![image](https://github.com/Angel-125/DSEV/assets/1559108/5fd52325-71c6-4ce4-88f2-f164af6d9263)

Maybe v3.**30** was intended, since the previous release was v3.20?

**Comment by JonnyOThan** [comment]
This seems likely:

> Maybe v3.30 was intended, since the previous release was v3.20?

The .version file still says 3.20 too: https://github.com/Angel-125/DSEV/blob/v3.3.0/GameData/WildBlueIndustries/DSEV/DSEV.version

**Comment by HebaruSan** [comment]
I guess GitHub and Discord aren't good ways to contact. Tried the forum.

- <https://forum.kerbalspaceprogram.com/topic/122162-min-ksp-1122-deep-space-exploration-vessels-build-nasa-inspired-ships-in-ksp/?do=findComment&comment=4358436>

**Comment by HebaruSan** [comment]
Thanks for the fix! 👍 

https://github.com/Angel-125/DSEV/releases/tag/v3.30.0
